"""empty message

Revision ID: 6ed098412b8b
Revises: 
Create Date: 2019-10-11 16:02:08.585042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed098412b8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('create_dttm', sa.DateTime(), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('recipe_id'),
    schema='cbschema'
    )
    op.create_table('steps',
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('step_num', sa.BigInteger(), nullable=False),
    sa.Column('info', sa.String(length=5000), nullable=True),
    sa.Column('create_dttm', sa.DateTime(), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['cbschema.recipes.recipe_id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'step_num'),
    schema='cbschema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steps', schema='cbschema')
    op.drop_table('recipes', schema='cbschema')
    # ### end Alembic commands ###
