"""empty message

Revision ID: 7eb0a3b46348
Revises: bf71d9491638
Create Date: 2019-10-12 12:01:33.314085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb0a3b46348'
down_revision = 'bf71d9491638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('create_dttm', sa.DateTime(), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['cbschema.recipes.recipe_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id'),
    schema='cbschema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients', schema='cbschema')
    # ### end Alembic commands ###
