"""empty message

Revision ID: ad82d2815a5e
Revises: 2cbe0cbb9103
Create Date: 2019-10-10 14:48:29.434761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad82d2815a5e'
down_revision = '2cbe0cbb9103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('create_dttm', sa.DateTime(), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('recipe_id'),
    schema='cbschema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes', schema='cbschema')
    # ### end Alembic commands ###
