"""empty message

Revision ID: bf71d9491638
Revises: 6825c21f1a00
Create Date: 2019-10-12 11:53:11.622397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf71d9491638'
down_revision = '6825c21f1a00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('create_dttm', sa.DateTime(), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('recipe_id'),
    schema='cbschema'
    )
    op.create_table('ingredients',
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('ingredient_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('create_dttm', sa.DateTime(), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['cbschema.recipes.recipe_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id'),
    schema='cbschema'
    )
    op.create_table('steps',
    sa.Column('recipe_id', sa.BigInteger(), nullable=False),
    sa.Column('step_num', sa.BigInteger(), nullable=False),
    sa.Column('info', sa.String(length=5000), nullable=True),
    sa.Column('create_dttm', sa.DateTime(), nullable=False),
    sa.Column('update_dttm', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['cbschema.recipes.recipe_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'step_num'),
    schema='cbschema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steps', schema='cbschema')
    op.drop_table('ingredients', schema='cbschema')
    op.drop_table('recipes', schema='cbschema')
    # ### end Alembic commands ###
