"""empty message

Revision ID: c143a4a97bf3
Revises: 7eb0a3b46348
Create Date: 2019-10-12 12:07:21.180434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c143a4a97bf3'
down_revision = '7eb0a3b46348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('notes', sa.String(length=5000), nullable=True), schema='cbschema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'notes', schema='cbschema')
    # ### end Alembic commands ###
