"""empty message

Revision ID: 0bad3f37c085
Revises: 7c8942879943
Create Date: 2019-11-06 20:30:21.760029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bad3f37c085'
down_revision = '7c8942879943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True), schema='cbschema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password', schema='cbschema')
    # ### end Alembic commands ###
