"""empty message

Revision ID: 1713ee6f32a4
Revises: 2c04a021adf2
Create Date: 2019-11-06 20:28:30.302294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1713ee6f32a4'
down_revision = '2c04a021adf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stuff', schema='cbschema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stuff', sa.VARCHAR(length=5), autoincrement=False, nullable=True), schema='cbschema')
    # ### end Alembic commands ###
