"""empty message

Revision ID: 2c04a021adf2
Revises: a4cb28545131
Create Date: 2019-11-06 20:28:11.447445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c04a021adf2'
down_revision = 'a4cb28545131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stuff', sa.String(length=5), nullable=True), schema='cbschema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stuff', schema='cbschema')
    # ### end Alembic commands ###
