"""empty message

Revision ID: 7c8942879943
Revises: 1713ee6f32a4
Create Date: 2019-11-06 20:30:04.681485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c8942879943'
down_revision = '1713ee6f32a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password', schema='cbschema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='cbschema')
    # ### end Alembic commands ###
