"""empty message

Revision ID: a4cb28545131
Revises: c143a4a97bf3
Create Date: 2019-11-06 19:49:37.703541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4cb28545131'
down_revision = 'c143a4a97bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=70), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('create_dttm', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    schema='cbschema'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='cbschema')
    # ### end Alembic commands ###
